apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret-{{ .Values.microservices.msapimadaptor.name  }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  secret: Wmprd1lUTTFOVEUzTVRBd1lqSm1ZbVEyTkRFeVpUUmxNREJoTW1OalpXSmtZMlE0Wmpnd1pqZ3dOak5qWkRGak1EaGpNV0k0WWpVM05HUXhPREU0TldVNVlXRmhPVGt6Tm1WaE9EQXlOVEEyTjJGaVpqSmtPVFprTVdNeU1HWTNZbUl3TWc9PQ==
  clientId: bDc3MWY1ZDNiZDQ4MGQ0YWJjOTM5ODE0ODBhNDc3N2YyZA==
  clientSecret: NWU0MWU5ZTlkNzZmNGE3MzkzMDI5Mjk2ZDNlMWM4YTQ=
