apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret-{{ .Values.microservices.mstmfserviceactivationandconfiguration.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  secret: WWpWbE1tSTVOVFZoTXpkbE56QmhPR013TkRRNVpXTmhZVEZsWW1Fd056RmpZamhtWW1aaU1qTTVObUZrTmpGak1HTmtNV05tTVRBeFpEWm1NelF4WTJVNU5XUmtNelZtTjJGaE4yTTRaRGN5WXpnM1pUUTFNMlE0TXpBMU5UQXhNR0pqWmpjM01qQTVZakEyTTJFek5EWTRNamMzWWpabE5UZzBNREpoTlRrPQ==
