apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret-{{ .Values.microservices.workflowengine.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  secret: TnpRek9EY3dOREZoWmpRek5qTTNPVEkxTlRZNE1UbGhaVEk0TWpjNE1qQTFPVGswTldVM01UbGlaRE13TTJFNU5XUmhaR1kzTURBd1pUSTNOamcwTldGbE1qZGpZV0UyTW1SbE5UZ3pOak00WkRFelpqVTNaV0UxTm1FeFpXRXlNMkl3TkRobVpUSmxOR1F4WW1WbU16VTFOV1JsWlRVMk4yUTJNV0ZtTkdVPQ==
  databasePassword: dlk5PHFKMyViQjA+bVI1PA==
